name:                99problems
version:             0.1.0.0
github:              "homebetter/99problems"
license:             BSD3
author:              "WangJie"
maintainer:          "wangjie@gosuncn.com"
copyright:           "2018 WangJie"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            99-Problems

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/wangjie@gosuncn.com/99problems#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  99problems-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 99problems

tests:
  99problems-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 99problems
